-- Migration 000007: Seed public crawling targets from CRAWL_SOURCE.md
-- org_id = NULL denotes Global Public Targets accessible by platform worker

INSERT INTO crawling_targets (source_name, source_type, target_url, check_interval_hours, is_active, org_id)
VALUES
    -- 1. Keterbukaan Informasi & Laporan Emiten Bursa (BEI / IDX)
    ('IDX Keterbukaan Informasi Publik', 'NEWS_ARTICLE', 'https://www.idx.co.id/id/berita/pengumuman', 6, true, NULL),
    ('IDX Sustainability Reports Hub', 'PDF_DOCUMENT', 'https://www.idx.co.id/id/perusahaan-tercatat/laporan-keberlanjutan', 24, true, NULL),

    -- 2. Portal Berita Finansial, Bisnis, dan CSR (RSS Feed)
    ('Google News RSS - CSR Perusahaan Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+perusahaan+Indonesia&hl=id&gl=ID&ceid=ID:id', 4, true, NULL),
    ('Bisnis.com RSS Feed - CSR & Finansial', 'NEWS_RSS', 'https://www.bisnis.com/rss', 4, true, NULL),
    ('Kontan.co.id RSS Feed - Keuangan & Industri', 'NEWS_RSS', 'https://www.kontan.co.id/rss', 4, true, NULL),
    ('Antara News RSS - Warta Ekonomi & Humaniora', 'NEWS_RSS', 'https://www.antaranews.com/rss/ekonomi', 4, true, NULL),
    ('Republika Online RSS - Filantropi & Zakat Korporasi', 'NEWS_RSS', 'https://www.republika.co.id/rss/ekonomi/syariah-filantropi', 4, true, NULL),

    -- 3. Portal Resmi BUMN & Press Release Korporasi
    ('Kementerian BUMN - Siaran Pers TJSL', 'BUMN_PORTAL', 'https://bumn.go.id/media/press-release', 12, true, NULL),
    ('Pertamina Newsroom - CSR & TJSL Updates', 'NEWS_ARTICLE', 'https://www.pertamina.com/id/news-room', 12, true, NULL),
    ('PLN Newsroom - Program CSR & Desa Berdaya', 'NEWS_ARTICLE', 'https://web.pln.co.id/media/siaran-pers', 12, true, NULL),
    ('Pelindo TJSL & Social Impact Newsroom', 'NEWS_ARTICLE', 'https://pelindo.co.id/media/berita', 12, true, NULL),

    -- 4. Portal Pengadaan & Hibah Lembaga Donor / Kedutaan (Grants)
    ('UNDP Indonesia Procurement Notices & Grants', 'GRANTS_PORTAL', 'https://procurement-notices.undp.org/', 24, true, NULL),
    ('Kedutaan Besar Australia - Direct Aid Program (DAP)', 'GRANTS_PORTAL', 'https://indonesia.embassy.gov.au/jkti/dap.html', 24, true, NULL),
    ('Kedutaan Besar Jepang - Hibah Grassroots (GGP)', 'GRANTS_PORTAL', 'https://www.id.emb-japan.go.jp/ggp.html', 24, true, NULL)
ON CONFLICT DO NOTHING;

-- Generated Seeds for 100 Top Indonesian Corporations (Google News & Antara News)
INSERT INTO crawling_targets (source_name, source_type, target_url, check_interval_hours, is_active, org_id)
VALUES
    ('Google News RSS - CSR Pertamina', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Pertamina&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Pertamina', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Pertamina', 6, true, NULL),
    ('Google News RSS - CSR Pertamina Geothermal Energy', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Pertamina+Geothermal+Energy&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Pertamina Geothermal Energy', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Pertamina+Geothermal+Energy', 6, true, NULL),
    ('Google News RSS - CSR Pertamina EP', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Pertamina+EP&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Pertamina EP', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Pertamina+EP', 6, true, NULL),
    ('Google News RSS - CSR Pertamina Hulu Energi', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Pertamina+Hulu+Energi&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Pertamina Hulu Energi', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Pertamina+Hulu+Energi', 6, true, NULL),
    ('Google News RSS - CSR Pertamina Patra Niaga', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Pertamina+Patra+Niaga&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Pertamina Patra Niaga', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Pertamina+Patra+Niaga', 6, true, NULL),
    ('Google News RSS - CSR PLN', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+PLN&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR PLN', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+PLN', 6, true, NULL),
    ('Google News RSS - CSR PLN Energi Gas', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+PLN+Energi+Gas&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR PLN Energi Gas', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+PLN+Energi+Gas', 6, true, NULL),
    ('Google News RSS - CSR PGN Perusahaan Gas Negara', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+PGN+Perusahaan+Gas+Negara&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR PGN Perusahaan Gas Negara', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+PGN+Perusahaan+Gas+Negara', 6, true, NULL),
    ('Google News RSS - CSR Inalum', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Inalum&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Inalum', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Inalum', 6, true, NULL),
    ('Google News RSS - CSR Bukit Asam', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Bukit+Asam&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Bukit Asam', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Bukit+Asam', 6, true, NULL),
    ('Google News RSS - CSR Antam Aneka Tambang', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Antam+Aneka+Tambang&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Antam Aneka Tambang', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Antam+Aneka+Tambang', 6, true, NULL),
    ('Google News RSS - CSR Kilang Pertamina Internasional', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Kilang+Pertamina+Internasional&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Kilang Pertamina Internasional', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Kilang+Pertamina+Internasional', 6, true, NULL),
    ('Google News RSS - CSR MIND ID', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+MIND+ID&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR MIND ID', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+MIND+ID', 6, true, NULL),
    ('Google News RSS - CSR Timah Tbk', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Timah+Tbk&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Timah Tbk', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Timah+Tbk', 6, true, NULL),
    ('Google News RSS - CSR Vale Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Vale+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Vale Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Vale+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Freeport Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Freeport+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Freeport Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Freeport+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Adaro Energy', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Adaro+Energy&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Adaro Energy', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Adaro+Energy', 6, true, NULL),
    ('Google News RSS - CSR Harbour Energy', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Harbour+Energy&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Harbour Energy', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Harbour+Energy', 6, true, NULL),
    ('Google News RSS - CSR Bank Mandiri', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Bank+Mandiri&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Bank Mandiri', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Bank+Mandiri', 6, true, NULL),
    ('Google News RSS - CSR Bank Rakyat Indonesia BRI', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Bank+Rakyat+Indonesia+BRI&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Bank Rakyat Indonesia BRI', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Bank+Rakyat+Indonesia+BRI', 6, true, NULL),
    ('Google News RSS - CSR Bank Negara Indonesia BNI', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Bank+Negara+Indonesia+BNI&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Bank Negara Indonesia BNI', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Bank+Negara+Indonesia+BNI', 6, true, NULL),
    ('Google News RSS - CSR Bank Central Asia BCA', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Bank+Central+Asia+BCA&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Bank Central Asia BCA', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Bank+Central+Asia+BCA', 6, true, NULL),
    ('Google News RSS - CSR Bank Kalbar', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Bank+Kalbar&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Bank Kalbar', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Bank+Kalbar', 6, true, NULL),
    ('Google News RSS - CSR Bank Syariah Indonesia BSI', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Bank+Syariah+Indonesia+BSI&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Bank Syariah Indonesia BSI', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Bank+Syariah+Indonesia+BSI', 6, true, NULL),
    ('Google News RSS - CSR Bank CIMB Niaga', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Bank+CIMB+Niaga&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Bank CIMB Niaga', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Bank+CIMB+Niaga', 6, true, NULL),
    ('Google News RSS - CSR Bank Danamon', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Bank+Danamon&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Bank Danamon', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Bank+Danamon', 6, true, NULL),
    ('Google News RSS - CSR Bank OCBC NISP', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Bank+OCBC+NISP&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Bank OCBC NISP', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Bank+OCBC+NISP', 6, true, NULL),
    ('Google News RSS - CSR Bank Permata', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Bank+Permata&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Bank Permata', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Bank+Permata', 6, true, NULL),
    ('Google News RSS - CSR Prudential Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Prudential+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Prudential Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Prudential+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR AIA Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+AIA+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR AIA Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+AIA+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Allianz Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Allianz+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Allianz Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Allianz+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Sun Life Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Sun+Life+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Sun Life Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Sun+Life+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Finnet Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Finnet+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Finnet Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Finnet+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR BPR Bank Bapas 69', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+BPR+Bank+Bapas+69&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR BPR Bank Bapas 69', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+BPR+Bank+Bapas+69', 6, true, NULL),
    ('Google News RSS - CSR Telkom Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Telkom+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Telkom Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Telkom+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Telkomsel', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Telkomsel&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Telkomsel', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Telkomsel', 6, true, NULL),
    ('Google News RSS - CSR Indosat Ooredoo Hutchison', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Indosat+Ooredoo+Hutchison&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Indosat Ooredoo Hutchison', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Indosat+Ooredoo+Hutchison', 6, true, NULL),
    ('Google News RSS - CSR XL Axiata', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+XL+Axiata&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR XL Axiata', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+XL+Axiata', 6, true, NULL),
    ('Google News RSS - CSR Smartfren', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Smartfren&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Smartfren', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Smartfren', 6, true, NULL),
    ('Google News RSS - CSR Global Infotech Solution', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Global+Infotech+Solution&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Global Infotech Solution', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Global+Infotech+Solution', 6, true, NULL),
    ('Google News RSS - CSR Unilever Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Unilever+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Unilever Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Unilever+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Nestle Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Nestle+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Nestle Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Nestle+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Indofood Sukses Makmur', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Indofood+Sukses+Makmur&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Indofood Sukses Makmur', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Indofood+Sukses+Makmur', 6, true, NULL),
    ('Google News RSS - CSR Danone Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Danone+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Danone Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Danone+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Mayora Indah', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Mayora+Indah&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Mayora Indah', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Mayora+Indah', 6, true, NULL),
    ('Google News RSS - CSR Wings Group', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Wings+Group&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Wings Group', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Wings+Group', 6, true, NULL),
    ('Google News RSS - CSR Sarihusada Generasi Mahardhika', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Sarihusada+Generasi+Mahardhika&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Sarihusada Generasi Mahardhika', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Sarihusada+Generasi+Mahardhika', 6, true, NULL),
    ('Google News RSS - CSR Coca-Cola Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Coca-Cola+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Coca-Cola Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Coca-Cola+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Sido Muncul', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Sido+Muncul&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Sido Muncul', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Sido+Muncul', 6, true, NULL),
    ('Google News RSS - CSR Kalbe Farma', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Kalbe+Farma&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Kalbe Farma', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Kalbe+Farma', 6, true, NULL),
    ('Google News RSS - CSR Astra International', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Astra+International&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Astra International', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Astra+International', 6, true, NULL),
    ('Google News RSS - CSR Toyota Astra Motor', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Toyota+Astra+Motor&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Toyota Astra Motor', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Toyota+Astra+Motor', 6, true, NULL),
    ('Google News RSS - CSR Honda Prospect Motor', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Honda+Prospect+Motor&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Honda Prospect Motor', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Honda+Prospect+Motor', 6, true, NULL),
    ('Google News RSS - CSR Suzuki Indomobil', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Suzuki+Indomobil&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Suzuki Indomobil', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Suzuki+Indomobil', 6, true, NULL),
    ('Google News RSS - CSR Hyundai Motor Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Hyundai+Motor+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Hyundai Motor Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Hyundai+Motor+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Semen Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Semen+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Semen Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Semen+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Indocement Tunggal Prakarsa', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Indocement+Tunggal+Prakarsa&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Indocement Tunggal Prakarsa', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Indocement+Tunggal+Prakarsa', 6, true, NULL),
    ('Google News RSS - CSR Holcim Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Holcim+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Holcim Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Holcim+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Jasa Marga', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Jasa+Marga&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Jasa Marga', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Jasa+Marga', 6, true, NULL),
    ('Google News RSS - CSR Waskita Karya', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Waskita+Karya&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Waskita Karya', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Waskita+Karya', 6, true, NULL),
    ('Google News RSS - CSR Wijaya Karya WIKA', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Wijaya+Karya+WIKA&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Wijaya Karya WIKA', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Wijaya+Karya+WIKA', 6, true, NULL),
    ('Google News RSS - CSR Pembangunan Perumahan PP', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Pembangunan+Perumahan+PP&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Pembangunan Perumahan PP', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Pembangunan+Perumahan+PP', 6, true, NULL),
    ('Google News RSS - CSR Tower Bersama Infrastructure TBIG', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Tower+Bersama+Infrastructure+TBIG&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Tower Bersama Infrastructure TBIG', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Tower+Bersama+Infrastructure+TBIG', 6, true, NULL),
    ('Google News RSS - CSR Sinar Mas', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Sinar+Mas&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Sinar Mas', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Sinar+Mas', 6, true, NULL),
    ('Google News RSS - CSR Indah Kiat Pulp Paper', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Indah+Kiat+Pulp+Paper&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Indah Kiat Pulp Paper', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Indah+Kiat+Pulp+Paper', 6, true, NULL),
    ('Google News RSS - CSR Cirebon Power', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Cirebon+Power&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Cirebon Power', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Cirebon+Power', 6, true, NULL),
    ('Google News RSS - CSR Kawasan Industri Terpadu Batang', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Kawasan+Industri+Terpadu+Batang&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Kawasan Industri Terpadu Batang', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Kawasan+Industri+Terpadu+Batang', 6, true, NULL),
    ('Google News RSS - CSR Sinar Mas Agribusiness', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Sinar+Mas+Agribusiness&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Sinar Mas Agribusiness', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Sinar+Mas+Agribusiness', 6, true, NULL),
    ('Google News RSS - CSR Sawit Sumbermas Sarana', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Sawit+Sumbermas+Sarana&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Sawit Sumbermas Sarana', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Sawit+Sumbermas+Sarana', 6, true, NULL),
    ('Google News RSS - CSR FKS Multi Agro Sejahtera', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+FKS+Multi+Agro+Sejahtera&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR FKS Multi Agro Sejahtera', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+FKS+Multi+Agro+Sejahtera', 6, true, NULL),
    ('Google News RSS - CSR Astra Agro Lestari', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Astra+Agro+Lestari&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Astra Agro Lestari', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Astra+Agro+Lestari', 6, true, NULL),
    ('Google News RSS - CSR Perkebunan Nusantara PTPN', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Perkebunan+Nusantara+PTPN&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Perkebunan Nusantara PTPN', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Perkebunan+Nusantara+PTPN', 6, true, NULL),
    ('Google News RSS - CSR Wilmar Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Wilmar+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Wilmar Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Wilmar+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Alfamart', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Alfamart&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Alfamart', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Alfamart', 6, true, NULL),
    ('Google News RSS - CSR Indomaret', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Indomaret&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Indomaret', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Indomaret', 6, true, NULL),
    ('Google News RSS - CSR Tokopedia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Tokopedia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Tokopedia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Tokopedia', 6, true, NULL),
    ('Google News RSS - CSR Gojek GoTo Group', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Gojek+GoTo+Group&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Gojek GoTo Group', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Gojek+GoTo+Group', 6, true, NULL),
    ('Google News RSS - CSR Traveloka', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Traveloka&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Traveloka', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Traveloka', 6, true, NULL),
    ('Google News RSS - CSR MNC Group', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+MNC+Group&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR MNC Group', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+MNC+Group', 6, true, NULL),
    ('Google News RSS - CSR Bisnis Indonesia Group', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Bisnis+Indonesia+Group&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Bisnis Indonesia Group', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Bisnis+Indonesia+Group', 6, true, NULL),
    ('Google News RSS - CSR Trans Corp', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Trans+Corp&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Trans Corp', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Trans+Corp', 6, true, NULL),
    ('Google News RSS - CSR Emtek Group', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Emtek+Group&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Emtek Group', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Emtek+Group', 6, true, NULL),
    ('Google News RSS - CSR Agincourt Resources', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Agincourt+Resources&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Agincourt Resources', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Agincourt+Resources', 6, true, NULL),
    ('Google News RSS - CSR Freeport McMoRan Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Freeport+McMoRan+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Freeport McMoRan Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Freeport+McMoRan+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Indika Energy', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Indika+Energy&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Indika Energy', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Indika+Energy', 6, true, NULL),
    ('Google News RSS - CSR Medco Energi', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Medco+Energi&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Medco Energi', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Medco+Energi', 6, true, NULL),
    ('Google News RSS - CSR Jasa Raharja', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Jasa+Raharja&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Jasa Raharja', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Jasa+Raharja', 6, true, NULL),
    ('Google News RSS - CSR Asuransi Astra', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Asuransi+Astra&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Asuransi Astra', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Asuransi+Astra', 6, true, NULL),
    ('Google News RSS - CSR BPJS Ketenagakerjaan', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+BPJS+Ketenagakerjaan&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR BPJS Ketenagakerjaan', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+BPJS+Ketenagakerjaan', 6, true, NULL),
    ('Google News RSS - CSR Taspen', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Taspen&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Taspen', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Taspen', 6, true, NULL),
    ('Google News RSS - CSR Garuda Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Garuda+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Garuda Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Garuda+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Angkasa Pura', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Angkasa+Pura&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Angkasa Pura', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Angkasa+Pura', 6, true, NULL),
    ('Google News RSS - CSR Pelindo', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Pelindo&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Pelindo', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Pelindo', 6, true, NULL),
    ('Google News RSS - CSR Kereta Api Indonesia KAI', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Kereta+Api+Indonesia+KAI&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Kereta Api Indonesia KAI', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Kereta+Api+Indonesia+KAI', 6, true, NULL),
    ('Google News RSS - CSR Pupuk Indonesia', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Pupuk+Indonesia&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Pupuk Indonesia', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Pupuk+Indonesia', 6, true, NULL),
    ('Google News RSS - CSR Petrokimia Gresik', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Petrokimia+Gresik&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Petrokimia Gresik', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Petrokimia+Gresik', 6, true, NULL),
    ('Google News RSS - CSR Chandra Asri Petrochemical', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Chandra+Asri+Petrochemical&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Chandra Asri Petrochemical', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Chandra+Asri+Petrochemical', 6, true, NULL),
    ('Google News RSS - CSR Baznas', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Baznas&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Baznas', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Baznas', 6, true, NULL),
    ('Google News RSS - CSR Sucofindo', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+Sucofindo&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR Sucofindo', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+Sucofindo', 6, true, NULL),
    ('Google News RSS - CSR PMLI Pendidikan Maritim Logistik', 'NEWS_RSS', 'https://news.google.com/rss/search?q=CSR+PMLI+Pendidikan+Maritim+Logistik&hl=id&gl=ID&ceid=ID:id', 6, true, NULL),
    ('Antara News Feed - CSR PMLI Pendidikan Maritim Logistik', 'NEWS_ARTICLE', 'https://www.antaranews.com/search?q=CSR+PMLI+Pendidikan+Maritim+Logistik', 6, true, NULL)
ON CONFLICT DO NOTHING;
